// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration with your actual credentials
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOYgRxdjE6SpVbvHVU43Epj1h8tBHcyI',
    appId: '1:706760995742:web:cbdd3d86ba058ba7c51c8f',
    messagingSenderId: '706760995742',
    projectId: 'raya-b7f0e',
    authDomain: 'raya-b7f0e.firebaseapp.com',
    storageBucket: 'raya-b7f0e.firebasestorage.app',
    measurementId: 'G-T9JND9P1YF',
  );

  // Using the same project credentials for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOYgRxdjE6SpVbvHVU43Epj1h8tBHcyI',
    appId: '1:706760995742:web:cbdd3d86ba058ba7c51c8f',
    messagingSenderId: '706760995742',
    projectId: 'raya-b7f0e',
    storageBucket: 'raya-b7f0e.firebasestorage.app',
  );

  // Using the same project credentials for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOYgRxdjE6SpVbvHVU43Epj1h8tBHcyI',
    appId: '1:706760995742:web:cbdd3d86ba058ba7c51c8f',
    messagingSenderId: '706760995742',
    projectId: 'raya-b7f0e',
    storageBucket: 'raya-b7f0e.firebasestorage.app',
    iosClientId: '706760995742-app-client-id', // This should be replaced with the actual iOS client ID
    iosBundleId: 'com.belatuk.raya', // This should be replaced with your actual bundle ID
  );

  // Using the same project credentials for macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOYgRxdjE6SpVbvHVU43Epj1h8tBHcyI',
    appId: '1:706760995742:web:cbdd3d86ba058ba7c51c8f',
    messagingSenderId: '706760995742',
    projectId: 'raya-b7f0e',
    storageBucket: 'raya-b7f0e.firebasestorage.app',
    iosClientId: '706760995742-app-client-id', // This should be replaced with the actual macOS client ID
    iosBundleId: 'com.belatuk.raya', // This should be replaced with your actual bundle ID
  );
}
